../osvvm/OsvvmScriptSettingsPkg.vhd
../osvvm/TextUtilPkg.vhd
../osvvm/ResolutionPkg.vhd
../osvvm/NamePkg.vhd
../osvvm/OsvvmGlobalPkg.vhd
../osvvm/VendorCovApiPkg.vhd
../osvvm/TranscriptPkg.vhd
../osvvm/AlertLogPkg.vhd
../osvvm/NameStorePkg.vhd
../osvvm/MessageListPkg.vhd
../osvvm/SortListPkg_int.vhd
../osvvm/RandomBasePkg.vhd
../osvvm/RandomPkg.vhd
../osvvm/RandomProcedurePkg.vhd
../osvvm/CoveragePkg.vhd
../osvvm/ResizePkg.vhd
../osvvm/ScoreboardGenericPkg.vhd
../osvvm/ScoreboardPkg_slv.vhd
../osvvm/ScoreboardPkg_int.vhd
../osvvm/ScoreboardPkg_slv_c.vhd
../osvvm/ScoreboardPkg_int_c.vhd
../osvvm/MemorySupportPkg.vhd
../osvvm/MemoryGenericPkg.vhd
../osvvm/MemoryPkg.vhd
../osvvm/MemoryPkg_c.vhd
../osvvm/MemoryPkg_orig_c.vhd
../osvvm/TbUtilPkg.vhd
../osvvm/ReportPkg.vhd
../osvvm/OsvvmTypesPkg.vhd
../osvvm/OsvvmContext.vhd 
../osvvm/OsvvmScriptSettingsPkg_generated.vhd
../osvvm/OsvvmScriptSettingsPkg_default.vhd
